version: '3.7'

services:
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    image: traefik:v2.5
    restart: always
    command:
      - --api.insecure=true 
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=web
      - --entrypoints.web.address=:80
    networks: 
      - web
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  web:
    name: web
    driver: bridge
  default:
    external: true
    name: web
